### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by huanghongjin** [yangchaojiang/DemoLoadView#2]
Process: test_webview_demo.example.com.myapplication, PID: 25531
                                                                                             java.lang.RuntimeException: Unable to instantiate application com.example.com.myapplication.App: java.lang.ClassNotFoundException: Didn't find class "com.example.com.myapplication.App" on path: DexPathList[[zip file "/data/app/test_webview_demo.example.com.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/test_webview_demo.example.com.myapplication-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:680)
                                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6395)
                                                                                                 at android.app.ActivityThread.access$1800(ActivityThread.java:229)
                                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                                 at

**Comment by yangchaojiang** [comment]
不好意思，上上传是app 的build.gradle  文件里   修改  applicationId "com.example.com.myapplication"
你是试一下

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/27415071-8b3b448c-5737-11e7-97a3-a77dbd54666d.png)

**Comment by huanghongjin** [comment]
还是报错，

**Comment by huanghongjin** [comment]
Suppressed: java.lang.ClassNotFoundException: com.example.com.myapplication.App
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                   		... 12 more

是不是少了 com.example.com.myapplication.App 文件

**Comment by huanghongjin** [comment]
<application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

这个Application 有没有其他设置？还是说随便一个Application 都可以替代

**Comment by yangchaojiang** [comment]
app 文件没有上传gtihub  你新建一个app 可以的

**Comment by yangchaojiang** [comment]
说随便一个Application 都可以，在oncreate 方式你 进行配置代码就行了

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/27415561-2a8f099a-573a-11e7-91a9-edd7479b4541.png)

**Comment by huanghongjin** [comment]
3q

**Comment by yangchaojiang** [comment]
不客气， 我应该谢谢你。 谢谢你反馈
